# Generated by Django 4.2.4 on 2023-08-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_adverts', '0003_remove_advertisement_author_advertisement_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='user',
        ),
    ]
