# Generated by Django 4.2.4 on 2023-08-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_adverts', '0005_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='photo',
            field=models.ImageField(default=1, upload_to='my_adverts', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
